# Generated by Django 5.1.5 on 2025-11-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='target_user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='property',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
