# Generated by Django 5.2.9 on 2025-12-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_propertyreview_property_invoice_offer'),
        ('property', '0004_property_air_conditioning_property_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to='property.property'),
        ),
    ]
