# Generated by Django 5.1.5 on 2025-11-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
    ]
