# Generated by Django 5.2.9 on 2025-12-22 19:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0004_property_air_conditioning_property_breakfast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoIncentive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('discount', 'Discount'), ('credit', 'Credit'), ('reward_points', 'Reward Points')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount amount or credit value', max_digits=10)),
                ('percentage', models.IntegerField(blank=True, help_text='Discount percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('requires_green_property', models.BooleanField(default=True)),
                ('min_stay_nights', models.IntegerField(default=1)),
                ('max_uses_per_user', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SustainableExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('outdoor', 'Outdoor Activities'), ('cultural', 'Cultural Experiences'), ('food', 'Local Food & Dining'), ('shopping', 'Sustainable Shopping'), ('transport', 'Green Transportation'), ('education', 'Educational Tours')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('carbon_neutral', models.BooleanField(default=False)),
                ('community_supported', models.BooleanField(default=False)),
                ('eco_certified', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_type', models.CharField(choices=[('walk', 'Walking'), ('bike', 'Bicycle'), ('bus', 'Bus'), ('train', 'Train'), ('car', 'Car'), ('electric_car', 'Electric Car'), ('flight_domestic', 'Domestic Flight'), ('flight_international', 'International Flight')], max_length=30)),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stay_duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('transport_carbon', models.FloatField(default=0, help_text='CO2 from transport in kg')),
                ('accommodation_carbon', models.FloatField(default=0, help_text='CO2 from accommodation in kg')),
                ('total_carbon', models.FloatField(default=0, help_text='Total CO2 in kg')),
                ('offset_purchased', models.BooleanField(default=False)),
                ('offset_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbon_calculations', to='property.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carbon_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcoIncentiveUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='sustainability.ecoincentive')),
                ('property_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_incentive_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='GreenCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('level', models.CharField(blank=True, choices=[('bronze', 'Bronze - Basic Sustainability'), ('silver', 'Silver - Advanced Sustainability'), ('gold', 'Gold - Exceptional Sustainability')], max_length=20, null=True)),
                ('energy_saving', models.BooleanField(default=False, help_text='LED lights, solar panels, energy-efficient appliances')),
                ('water_conservation', models.BooleanField(default=False, help_text='Low-flow fixtures, rainwater harvesting')),
                ('recycling_program', models.BooleanField(default=False, help_text='Recycling bins, composting')),
                ('reduced_plastic', models.BooleanField(default=False, help_text='No single-use plastics')),
                ('renewable_energy', models.BooleanField(default=False, help_text='Solar, wind, or other renewable sources')),
                ('organic_amenities', models.BooleanField(default=False, help_text='Organic toiletries, eco-friendly cleaning')),
                ('local_sourcing', models.BooleanField(default=False, help_text='Local food, products from local businesses')),
                ('green_transportation', models.BooleanField(default=False, help_text='Bike rentals, EV charging stations')),
                ('description', models.TextField(blank=True, help_text='Describe your sustainability practices')),
                ('documentation', models.JSONField(blank=True, default=dict, help_text='Links to certificates, photos, etc.')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Certificate valid until', null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_certifications', to=settings.AUTH_USER_MODEL)),
                ('property_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='green_certification', to='property.property')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('electricity_kwh', models.FloatField(help_text='Electricity usage in kWh', validators=[django.core.validators.MinValueValidator(0)])),
                ('water_liters', models.FloatField(help_text='Water usage in liters', validators=[django.core.validators.MinValueValidator(0)])),
                ('gas_kwh', models.FloatField(default=0, help_text='Gas usage in kWh', validators=[django.core.validators.MinValueValidator(0)])),
                ('occupancy_rate', models.FloatField(default=0, help_text='Percentage of property occupied', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('number_of_guests', models.IntegerField(default=0)),
                ('outdoor_temperature', models.FloatField(blank=True, help_text='Average outdoor temp in Celsius', null=True)),
                ('is_anomaly', models.BooleanField(default=False, help_text='Flagged by AI as unusual usage')),
                ('ai_recommendation', models.TextField(blank=True, help_text='AI-generated suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_usage', to='property.property')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('property_obj', 'date')},
            },
        ),
    ]
