import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import LoginModal from "./components/Modals/LoginModal";
import SignUpModal from "./components/Modals/SignUpModal";
import AddPropertyModal from "./components/Modals/AddPropertyModal";
// import SignInButton from "./components/Modals/SignInButton";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Toaster } from 'react-hot-toast';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart Room Booking System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Content =(
      <p>hahah</p>
  )
  return (
    <ClerkProvider>
      <>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Navbar/>
            <AddPropertyModal/>
            <Toaster />
            <div className="pt-24">
            {children}
            </div>
            {/* <Modals
            label="sadsa"
            Content={Content}
            isOpen={true}
            /> */}
            {/* <LoginModal/> */}
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            
            {/* <SignUpModal/> */}
          </body>
        </html>
      </>
    </ClerkProvider>
  );
}
