# Generated by Django 5.2.9 on 2025-12-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_role',
            field=models.CharField(choices=[('guest', 'Guest'), ('host', 'Host')], default='guest', max_length=10),
        ),
    ]
